default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: run-tests
        name: run pytest suite
        entry: uv run pytest -p no:cacheprovider
        language: system
        pass_filenames: false
        stages: [pre-commit]
